const { Router } = require("express");
const { companyRoutes } = require("./companies/companies.routes");
const { userRoutes } = require("./users/users.routes");
const { roleRoutes } = require("./roles/roles.routes");
const { permissionRoutes } = require("./permissions/permissions.routes");
const { teamRoutes } = require("./teams/teams.routes");
const { projectRoutes } = require("./projects/projects.routes");
const { unitRoutes } = require("./units/units.routes");
const { bookingRoutes } = require("./bookings/bookings.routes");
const { customerRoutes } = require("./customers/customers.routes");
const { taskRoutes } = require("./tasks/tasks.routes");
const { blockRoutes } = require("./blocks/blocks.routes");
const { floorRoutes } = require("./floors/floors.routes");
const { holdRoutes } = require("./holds/holds.routes");
const { rateCardRoutes } = require("./rate-cards/rate-cards.routes");
const { rateCardChargeRoutes } = require("./rate-card-charges/rate-card-charges.routes");
const { plcRoutes } = require("./plcs/plcs.routes");
const { inventoryRoutes } = require("./inventory/inventory.routes");
const { driverRoutes } = require("./drivers/drivers.routes");
const { siteVisitRoutes } = require("./site-visits/site-visits.routes");
const { costSheetRoutes } = require("./cost-sheets/cost-sheets.routes");
const { tokenRoutes } = require("./tokens/tokens.routes");
const { approvalRequestRoutes } = require("./approval-requests/approval-requests.routes");
const { applicantRoutes } = require("./applicants/applicants.routes");
const { kycDocumentRoutes } = require("./kyc-documents/kyc-documents.routes");
const { offerRoutes } = require("./offers/offers.routes");
const { paymentPlanTemplateRoutes } = require("./payment-plan-templates/payment-plan-templates.routes");
const { paymentPlanRoutes } = require("./payment-plans/payment-plans.routes");
const { milestoneRoutes } = require("./milestones/milestones.routes");
const { demandRoutes } = require("./demands/demands.routes");
const { receiptRoutes } = require("./receipts/receipts.routes");
const { refundRoutes } = require("./refunds/refunds.routes");
const { ledgerRoutes } = require("./ledger/ledger.routes");
const { ticketRoutes } = require("./tickets/tickets.routes");
const { collectionsRoutes } = require("./collections/collections.routes");
const { brokerRoutes } = require("./brokers/brokers.routes");
const { brokerProjectRoutes } = require("./broker-projects/broker-projects.routes");
const { commissionRoutes } = require("./commissions/commissions.routes");
const { leadDisputeRoutes } = require("./lead-disputes/lead-disputes.routes");
const { reportsRoutes } = require("./reports/reports.routes");
const { campaignRoutes } = require("./campaigns/campaigns.routes");
const { conversationRoutes } = require("./conversations/conversations.routes");
const { callRoutes } = require("./calls/calls.routes");
const { messageRoutes } = require("./messages/messages.routes");
const { whatsappRoutes } = require("./whatsapp/whatsapp.routes");
const { emailRoutes } = require("./email/email.routes");

const moduleRoutes = Router();

moduleRoutes.use("/companies", companyRoutes);
moduleRoutes.use("/users", userRoutes);
moduleRoutes.use("/roles", roleRoutes);
moduleRoutes.use("/permissions", permissionRoutes);
moduleRoutes.use("/teams", teamRoutes);
moduleRoutes.use("/projects", projectRoutes);
moduleRoutes.use("/units", unitRoutes);
moduleRoutes.use("/bookings", bookingRoutes);
moduleRoutes.use("/customers", customerRoutes);
moduleRoutes.use("/tasks", taskRoutes);
moduleRoutes.use("/blocks", blockRoutes);
moduleRoutes.use("/floors", floorRoutes);
moduleRoutes.use("/holds", holdRoutes);
moduleRoutes.use("/rate-cards", rateCardRoutes);
moduleRoutes.use("/rate-card-charges", rateCardChargeRoutes);
moduleRoutes.use("/plcs", plcRoutes);
moduleRoutes.use("/inventory", inventoryRoutes);
moduleRoutes.use("/drivers", driverRoutes);
moduleRoutes.use("/site-visits", siteVisitRoutes);
moduleRoutes.use("/cost-sheets", costSheetRoutes);
moduleRoutes.use("/tokens", tokenRoutes);
moduleRoutes.use("/approval-requests", approvalRequestRoutes);
moduleRoutes.use("/applicants", applicantRoutes);
moduleRoutes.use("/kyc-documents", kycDocumentRoutes);
moduleRoutes.use("/offers", offerRoutes);
moduleRoutes.use("/payment-plan-templates", paymentPlanTemplateRoutes);
moduleRoutes.use("/payment-plans", paymentPlanRoutes);
moduleRoutes.use("/milestones", milestoneRoutes);
moduleRoutes.use("/demands", demandRoutes);
moduleRoutes.use("/receipts", receiptRoutes);
moduleRoutes.use("/refunds", refundRoutes);
moduleRoutes.use("/ledger", ledgerRoutes);
moduleRoutes.use("/tickets", ticketRoutes);
moduleRoutes.use("/collections", collectionsRoutes);
moduleRoutes.use("/brokers", brokerRoutes);
moduleRoutes.use("/broker-projects", brokerProjectRoutes);
moduleRoutes.use("/commissions", commissionRoutes);
moduleRoutes.use("/lead-disputes", leadDisputeRoutes);
moduleRoutes.use("/reports", reportsRoutes);
moduleRoutes.use("/campaigns", campaignRoutes);
moduleRoutes.use("/conversations", conversationRoutes);
moduleRoutes.use("/calls", callRoutes);
moduleRoutes.use("/messages", messageRoutes);
moduleRoutes.use("/whatsapp", whatsappRoutes);
moduleRoutes.use("/email", emailRoutes);

module.exports = { moduleRoutes };
